export const GET_CITIES_START = "GET_CITIES_START";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const GET_CITIES_ERROR = "GET_CITIES_ERROR";
export const GET_FILTER_CITIES_START = "GET_FILTER_CITIES_START";
export const GET_FILTER_CITIES_SUCCESS = "GET_FILTER_CITIES_SUCCESS";
export const GET_FILTER_CITIES_ERROR = "GET_FILTER_CITIES_ERROR";
